name: Create Production Release

on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Create binary for multiplatform
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno2
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install
        run: deno i

      - name: Compile
        run: deno compile --allow-read --allow-net -o build/ ./chat.ts
      
      - name: Version (Linux and macOS)
        if: matrix.os != 'windows-latest'
        id: get_version_unix
        run: |
          echo "version=stable-$(date +%s)" >> $GITHUB_ENV

      - name: Version (Windows)
        if: matrix.os == 'windows-latest'
        id: get_version_win
        run: |
          echo "version=stable-$((Get-Date).Ticks)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: GH Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: tism-ai-${{ env.version }}-${{ matrix.os }}
          path: build
      
      - name: Rename files (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: |
          cd build && mv -v chat tism-ai-${{ env.version }}-${{ matrix.os }}
      
      - name: Rename files (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd build && mv chat.exe tism-ai-${{ env.version }}-${{ matrix.os }}.exe
        shell: pwsh

      - name: Upload Artifact to Release Tag (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/tism-ai-${{ env.version }}-${{ matrix.os }}.exe
      
      - name: Upload Artifact to Release Tag (Linux + MacOS)
        if: matrix.os != 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/tism-ai-${{ env.version }}-${{ matrix.os }}
      