name: Release Production Tag Build 

on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Build Artefact
    runs-on: ubuntu-24.04

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "deno i"

      - name: Build step
        run: "deno compile --allow-read --allow-net ./chat.ts"